### ISSUE TITLE
Login page frontend

### ISSUE THREAD

**Issue by RajneshB** [RajneshB/NITCONF-Evening_batch-Group_2#3]
Implement the design for login page for program committee.
- [x] Implement the design for the client side
- [x] Import the navigation bar component
- [x] implement the inputs needed as mentioned in the [Function 3.1.3.1](https://github.com/RajneshB/NITCONF-Evening_batch-Group_2#312-stimulusaction-sequences)
- [x] Implement the axios functions to fetch the details from the back-end

**Comment by zEvoker** [comment]
Remove the 'Remember me' option
